services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: 'llmbackend'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'llm-37121322'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d llmbackend -h to-backend-postgres -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5
    
    networks:
      - app-network
  payment_services:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: llm_solution
    restart: always
    image: llm_solution:v1.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: 'postgresql://postgres:llm-37121322@db:5432/llmbackend'
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
