services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:${DB_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME} -h to-backend-postgres -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  payment_services:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: llm_solution
    restart: always
    image: llm_solution:v1.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
networks:
  app-network:
    driver: bridge
